version: '3.3'
services:

    nginx:
        image: nginx:latest
        restart: always
        container_name: nginx
        ports:
            - "8080:80"
            - "443:443"

        volumes:
            - ./Nginx/core:/etc/nginx/conf.d
            - ./www:/var/www/
            - ./Nginx/Logs:/var/log/nginx/
            - ./html:/usr/share/nginx/html/
            - ./Nginx/conf/nginx.conf:/etc/nginx/nginx.conf

        links:
            - php
            
    mysql:
        image: percona
        restart: always
        container_name: mysql
#        command: mysqld --innodb-flush-method=O_DSYNC --innodb-use-native-aio=OFF --log_bin=ON
        ports:
            - "33306:3306"

        environment:

            - MYSQL_ROOT_PASSWORD=chd8h14
            - MYSQL_DATABASE=magento2
            - MYSQL_USER=magento2
            - MYSQL_PASSWORD=magento2
            
        volumes:
            - ./MySQL:/var/lib/mysql
            
        command:  --character-set-server=utf8
                  --key-buffer-size=8M
                  --max-connections=30
                  --query-cache-size=4M
                  --query-cache-limit=512K
                  --thread-stack=128K
                  --performance-schema=0
                  --show-compatibility-56=1
    php:

        build: PHP
        restart: always
        container_name: php-fpm

        volumes:
            - ./www:/var/www

        links:
            - mysql
